# 机柜部署图生成工具 - 字段映射配置文件
# 
# 此文件用于定义CSV文件字段与程序内部字段的映射关系
# 您可以根据实际的CSV文件格式修改此配置

# 字段映射配置
field_mappings:
  # 默认格式（原新格式）
  default:
    name: "默认格式"
    description: "标准的机柜部署CSV格式"
    required_fields: ["资产编号", "机房", "机柜", "U位"]
    field_mapping:
      "资产编号": "资产编号"
      "区域": "区域"
      "子区": "子区"
      "设备用途": "设备用途"
      "设备名": "设备名"
      "型号": "型号"
      "设备高度": "设备高度"
      "机房": "机房"
      "机柜": "机柜"
      "U位": "U位"
      "厂商": "厂商"

  # 旧格式
  legacy:
    name: "旧格式"
    description: "兼容旧版本的CSV格式"
    required_fields: ["序号", "机柜号", "U位"]
    field_mapping:
      "序号": "资产编号"
      "设备名": "设备名"
      "型号": "型号"
      "设备高度": "设备高度"
      "类型": "设备用途"
      "机柜号": "机柜"
      "U位": "U位"

  # 新格式：支持起始U（只使用起始U，忽略结束U）
  range_format:
    name: "起始U格式"
    description: "使用起始U字段确定设备U位，忽略结束U"
    required_fields: ["机房", "机柜", "起始U"]
    field_mapping:
      "序号": "资产编号"
      "设备名称": "设备名"
      "型号": "型号"
      "SN": "序列号"
      "资产编号": "资产编号"
      "区域": "区域"
      "子区": "子区"
      "设备用途": "设备用途"
      "设备名": "设备名"
      "设备高度": "设备高度"
      "机房": "机房"
      "机柜": "机柜"
      "起始U": "U位"
      "厂商": "厂商"

  # 自定义格式示例
  custom_example:
    name: "自定义格式示例"
    description: "展示如何定义自定义格式"
    enabled: false  # 设置为false表示不启用此格式
    required_fields: ["设备ID", "机柜编号", "位置"]
    field_mapping:
      "设备ID": "资产编号"
      "设备名称": "设备名"
      "设备型号": "型号"
      "高度": "设备高度"
      "用途": "设备用途"
      "机房编号": "机房"
      "机柜编号": "机柜"
      "位置": "U位"
      "制造商": "厂商"

# 默认值配置
default_values:
  "区域": "默认区域"
  "子区": "默认子区"
  "机房": "默认机房"
  "厂商": "未知厂商"
  "设备用途": "其他"

# 验证配置
validation:
  # 必需的内部字段（映射后必须存在的字段）
  required_internal_fields: ["机房", "机柜", "U位"]
  
  # 可选的内部字段
  optional_internal_fields: ["资产编号", "设备名", "型号", "设备高度", "设备用途", "区域", "子区", "厂商", "结束U位"]

# 格式检测配置
detection:
  # 格式检测的优先级（数字越小优先级越高）
  priority_order: ["range_format", "default", "legacy"]
  
  # 字段匹配阈值（必需字段的匹配比例）
  match_threshold: 0.8
  
  # 是否启用模糊匹配
  fuzzy_matching: true
  
  # 模糊匹配的相似度阈值
  similarity_threshold: 0.8

# 数据处理配置
processing:
  # 是否自动计算设备高度（当有起始U和结束U时）
  # 注意：当前逻辑只使用起始U，不使用结束U
  auto_calculate_height: false

  # 是否跳过空行
  skip_empty_rows: true

  # 是否跳过关键字段为空的行
  skip_invalid_rows: true

  # U位处理策略
  u_position_strategy: "start_u_only"  # 只使用起始U，忽略结束U
